class AppConstants {
  static const List<String> availableSkills = [
    'Flutter',
    'Dart',
    'Python',
    'Java',
    'C++',
    'C#',
    'Unity',
    'VHDL',
    'Firebase',
    'Supabase',
    'React',
    'Node.js',
    'UI/UX Design',
    'Data Science',
    'Machine Learning',
    'JavaScript',
    'TypeScript',
    'Go',
    'Rust',
    'Kotlin',
    'Swift',
    'AWS',
    'Google Cloud',
    'Azure',
    'Docker',
    'Kubernetes',
    'SQL',
    'NoSQL',
    'MongoDB',
    'PostgreSQL',
    'Vue.js',
    'Angular',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Blockchain',
    'Solidity',
    'C',
    'Ruby',
    'PHP',
    'Laravel',
    'Django',
    'Flask',
    'FastAPI',
    'Spring Boot',
    'Android Development',
    'iOS Development',
    'Cybersecurity',
    'Penetration Testing',
    'Data Engineering',
    'Game Development',
    'Unreal Engine',
    '3D Modeling',
    'Blender',
    'Figma',
    'Adobe XD',
    'Photoshop',
    'Illustrator',
    'Project Management',
    'Agile',
    'Scrum',
    'DevOps',
    'CI/CD',
    'Linux',
    'Git',
    'GitHub',
    'GitLab',
    'System Design',
    'Algorithms',
    'Data Structures',
  ];

  static const List<String> availableRoles = [
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'Mobile Developer',
    'iOS Developer',
    'Android Developer',
    'UI/UX Designer',
    'Product Manager',
    'Project Manager',
    'Data Scientist',
    'Data Engineer',
    'Machine Learning Engineer',
    'DevOps Engineer',
    'QA Tester',
    'Game Developer',
    'System Administrator',
    'Software Architect',
    'Business Analyst',
    'Security Analyst',
    'Blockchain Developer',
    'Hardware Engineer',
    'Embedded Systems Engineer',
    'Cloud Engineer',
    'Network Engineer',
    'Database Administrator',
  ];
}
